### PR TITLE
Solutions

### PR DESCRIPTION
**Pull request by boshika**

### CODE REVIEW

**Comment by RebootJeff** [comment]
Thanks for the pull request! Can you change it to target my "solutions" branch rather than my "master" branch?

**Comment by boshika** [comment]
Jeff,  would you know how to do that ?  it won't let me edit the branch...I
can close the request and re do it...

Boshika

On Tue, May 26, 2015 at 12:48 PM, Jeff Lee notifications@github.com wrote:

> Thanks for the pull request! Can you change it to target my "solutions"
> branch rather than my "master" branch?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RebootJeff/jsFunctions/pull/2#issuecomment-105645742.

## 

www.linkedin.com/in/boshikatara

**Comment by RebootJeff** [comment]
Yea maybe just redo the PR

On Tue, May 26, 2015 at 1:27 PM, Boshika Tara notifications@github.com
wrote:

> Jeff, would you know how to do that ? it won't let me edit the branch...I
> can close the request and re do it...
> 
> Boshika
> 
> On Tue, May 26, 2015 at 12:48 PM, Jeff Lee notifications@github.com
> wrote:
> 
> > Thanks for the pull request! Can you change it to target my "solutions"
> > branch rather than my "master" branch?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/RebootJeff/jsFunctions/pull/2#issuecomment-105645742
> > .
> 
> ## 
> 
> www.linkedin.com/in/boshikatara
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RebootJeff/jsFunctions/pull/2#issuecomment-105655589.

## 

-Jeff

**Comment by boshika** [comment]
Ok..

**Pull request closed without merging**
